plugins {
    id 'java-library'
}

dependencies {
    api platform(project(':platform-bom'))
    api project(':platform-core')
    api project(':platform-core-webmvc')
    api project(':platform-data')
    api project(':platform-security')
    api project(':platform-integration')
    api 'org.springframework.boot:spring-boot-starter-jdbc'
    api 'org.springframework.security:spring-security-crypto'
    implementation 'org.springframework.security:spring-security-oauth2-jose'
    api 'org.flywaydb:flyway-core'
    api 'org.springframework.boot:spring-boot-starter-validation'
    compileOnly 'org.springframework.boot:spring-boot-starter-data-redis'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-redis'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-oauth2-jose'
    testImplementation 'com.h2database:h2'
}
