plugins {
    id 'java-library'
}

dependencies {
    api platform(project(':platform-bom'))
    api project(':platform-core')
    api 'org.springframework.boot:spring-boot-starter-webflux'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
