plugins {
    id 'java-library'
}

dependencies {
    api platform(project(':platform-bom'))
    api project(':platform-ops')
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    compileOnly 'jakarta.annotation:jakarta.annotation-api'
    testImplementation 'jakarta.annotation:jakarta.annotation-api'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'com.redis:testcontainers-redis:2.2.2'
}
