plugins {
    id 'java-library'
}

dependencies {
    api platform(project(':platform-bom'))
    api project(':platform-ratelimit-core')
    api project(':platform-ratelimit-redis')
    api project(':platform-core-webmvc')
    api 'org.springframework.boot:spring-boot-starter-webmvc'
    compileOnly 'io.micrometer:micrometer-core'
    compileOnly project(':platform-security')
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'io.micrometer:micrometer-core'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
